let session=[],idx=0,locked=false,currentKey='',currentLevel='',currentTopic='';
const V = document.getElementById('view');
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function qs(level,topic){return DATA.questions.filter(q=>(!level||q.level===level)&&(!topic||q.topic===topic))}
function progress(level,topic){let a=qs(level,topic),d=a.filter(q=>state.done.includes(q.id)).length;return {d,n:a.length,p:a.length?Math.round(d/a.length*100):0}}
function home(){let total=DATA.questions.length,done=DATA.questions.filter(q=>state.done.includes(q.id)).length,p=Math.round(done/total*100);V.innerHTML=`<section class="hero"><h1>AI Foundations</h1><p>Master the foundations step by step: concise theory, 3 curated difficulty levels, and progress that resumes exactly where you stopped.</p></section><div class="quick"><button class="card mode" onclick="theoryHome()"><strong>Theory</strong><span>Compact reference of essential concepts</span></button><button class="card mode" onclick="mistakes()"><strong>Mistakes</strong><span>${state.mistakes.length} questions to review</span></button></div><div class="sectionTitle">Overall progress</div><div class="card"><div class="row"><div><div class="stat">${p}%</div><div class="muted">${done} of ${total} questions mastered</div></div><button class="listenSmall" onclick="settings()">⚙ Settings</button></div><div class="progress" style="margin-top:14px"><i style="width:${p}%"></i></div></div><div class="sectionTitle">Choose level</div>${levels.map(l=>levelCard(l)).join('')}`;nav('home')}
function levelCard(l){let a=qs(l),d=a.filter(q=>state.done.includes(q.id)).length,p=a.length?Math.round(d/a.length*100):0;return `<button class="card levelCard ${levelClass[l]}" onclick="levelHome('${l}')"><div><span class="levelTag">${l}</span><strong>${l==='Beginner'?'Build the foundation':l==='Intermediate'?'Apply the concepts':'Reason across concepts'}</strong><small>${d}/${a.length} completed · all 10 course sections</small></div><b>${p}%</b></button>`}
function levelHome(l){currentLevel=l;V.innerHTML=`<button class="back" onclick="home()">← Dashboard</button><div class="levelHead ${levelClass[l]}"><span class="levelTag">${l}</span><h2>${l==='Beginner'?'Know what each idea means':l==='Intermediate'?'Know when and how to use it':'Connect ideas and make sound choices'}</h2><p>Every core section of Foundations of AI is represented below. Advanced contains 10 reasoning questions per section.</p></div>${topics.map((t,i)=>topicCard(l,t,i)).join('')}`;nav('practice')}
function topicCard(l,t,i){let x=progress(l,t),key=l+'|'+t,pos=state.positions[key]||0;let next=Math.min(pos+1,x.n);return `<button class="card topicProgress" onclick="startTopic('${l}',${i})"><div class="topicNum">${i+1}</div><div class="grow"><b>${t}</b><small>${x.d}/${x.n} mastered · ${x.p}%${x.n&&x.d<x.n?' · Continue at '+next:''}</small><div class="progress mini"><i style="width:${x.p}%"></i></div></div><span>›</span></button>`}
function theoryHome(){V.innerHTML=`<button class="back" onclick="home()">← Dashboard</button><div class="sectionTitle">Theory · essential reference</div><div class="card theoryIntro"><h2>Everything you need to recognize</h2><p>Short, precise definitions and key distinctions. Use 🔊 to listen.</p></div>${topics.map((t,i)=>{let n=theory[t].length,pos=state.theoryPos[t]||0;return `<button class="card topicProgress" onclick="theoryTopic(${i})"><div class="topicNum">${i+1}</div><div class="grow"><b>${t}</b><small>${n} key ideas${pos?' · Continue at '+Math.min(pos+1,n):''}</small></div><span>›</span></button>`}).join('')}`;nav('theory')}
function theoryTopic(i){let t=topics[i],items=theory[t],pos=Math.min(state.theoryPos[t]||0,items.length-1);V.innerHTML=`<div class="quizTop"><button class="back" onclick="theoryHome()">← Theory</button><span class="muted">${pos+1} / ${items.length}</span></div><div class="progress"><i style="width:${Math.round((pos+1)/items.length*100)}%"></i></div><section class="qcard theoryCard"><div class="eyebrow">${t}</div><h2>${esc(items[pos][0])}</h2><p class="definition">${esc(items[pos][1])}</p><div class="theoryKey"><b>Key idea</b>${keyIdea(items[pos][0],items[pos][1])}</div><div class="actionRow"><button class="listen" onclick="speakTheory(${i},${pos})">🔊 Listen</button><button class="primary" onclick="nextTheory(${i},${pos})">${pos===items.length-1?'Finish':'Next →'}</button></div></section>`;nav('theory')}
function keyIdea(term,def){if(term.includes('RAG vs'))return 'Ask: does the method add context at query time, or change model parameters?';if(term==='Precision')return 'Start from predicted positives.';if(term==='Recall')return 'Start from actual positives.';if(term==='Overfitting')return 'Excellent training performance does not guarantee good performance on new data.';if(term==='Inference')return 'Training learns; inference uses what was learned.';return 'Be able to explain this concept in one sentence and recognize it in a simple example.'}
function nextTheory(i,pos){let t=topics[i],n=theory[t].length;if(pos<n-1){state.theoryPos[t]=pos+1;save();theoryTopic(i)}else{state.theoryPos[t]=n;save();theoryHome()}}
function startTopic(l,i){currentLevel=l;currentTopic=topics[i];currentKey=l+'|'+currentTopic;session=qs(l,currentTopic);idx=Math.min(state.positions[currentKey]||0,Math.max(0,session.length-1));showQ()}
function startLevel(l){currentLevel=l;currentTopic='';currentKey=l+'|ALL';session=qs(l);idx=Math.min(state.positions[currentKey]||0,Math.max(0,session.length-1));showQ()}
function mistakes(){let ids=state.mistakes;session=DATA.questions.filter(q=>ids.includes(q.id));currentLevel='Mistakes';currentTopic='';currentKey='mistakes';idx=0;if(!session.length){V.innerHTML=`<button class="back" onclick="home()">← Dashboard</button><div class="card"><h2>No mistakes waiting</h2><p class="muted">Questions you miss will appear here automatically.</p></div>`;nav('mistakes');return}showQ();nav('mistakes')}
function shuffledQuestion(q){if(q._display)return q._display;let items=q.options.map((text,i)=>({text,correct:i===q.answer}));for(let i=items.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}q._display={options:items.map(x=>x.text),answer:items.findIndex(x=>x.correct)};return q._display}
function showQ(){speechSynthesis.cancel();locked=false;if(!session.length){levelHome(currentLevel);return}if(idx>=session.length){V.innerHTML=`<div class="card"><div class="eyebrow">Section complete</div><h2>Nice work.</h2><p class="muted">You finished this section.</p><button class="primary" onclick="levelHome('${currentLevel}')">Back to ${currentLevel}</button></div>`;return}let q=session[idx],d=shuffledQuestion(q),pct=Math.round(idx/session.length*100);V.innerHTML=`<div class="quizTop"><button class="back" onclick="${currentLevel==='Mistakes'?'home()':`levelHome('${currentLevel}')`}">← Exit</button><span class="muted">${idx+1} / ${session.length}</span></div><div class="progress"><i style="width:${pct}%"></i></div><section class="qcard"><div class="qMeta"><div class="eyebrow">${q.level} · ${q.topic}</div><button class="listenSmall" onclick="speakQuestion()">🔊 Listen</button></div><div class="q">${esc(q.q)}</div><div class="answers">${d.options.map((o,i)=>`<button class="answer" onclick="choose(${i},this)"><span class="letter">${d.options.length===2?(o==='True'?'T':'F'):'ABCD'[i]}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="hint" id="hint"><b>Hint</b>${esc(q.hint)}</div><div class="explain" id="explain"><b>Exactly.</b> ${esc(d.options[d.answer])}</div><div class="audioOpts"><label><input type="checkbox" ${state.settings.autoListen?'checked':''} onchange="toggleAuto(this.checked)"> Auto Listen</label><span>${state.settings.speed}×</span></div></section>`;if(state.settings.autoListen)setTimeout(speakQuestion,250);nav(currentLevel==='Mistakes'?'mistakes':'practice')}
function choose(i,el){if(locked)return;let q=session[idx],d=shuffledQuestion(q);state.attempts++;if(i===d.answer){locked=true;el.classList.add('correct');state.correct++;if(!state.done.includes(q.id))state.done.push(q.id);state.mistakes=state.mistakes.filter(x=>x!==q.id);document.getElementById('explain').style.display='block';if(currentKey&&!currentKey.includes('mistakes'))state.positions[currentKey]=idx+1;save();setTimeout(()=>{idx++;showQ()},900)}else{el.classList.add('wrong');el.disabled=true;if(!state.mistakes.includes(q.id))state.mistakes.push(q.id);document.getElementById('hint').style.display='block';save()}}

function nav(n){document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.nav===n))}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>({home,theory:theoryHome,practice:()=>levelHome('Beginner'),mistakes}[b.dataset.nav]()));home();
